sudo: required
language: go
go_import_path: github.com/redhat-cop/cert-utils-operator
go:
- "1.11"
env:
  - DEP_VERSION=0.5.0

before_install:
  - openssl aes-256-cbc -K $encrypted_fa8b1278af8d_key -iv $encrypted_fa8b1278af8d_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key 
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - travis_retry dep ensure
  - curl -LO https://git.io/get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: make travis-latest-deploy
    on:
      repo: redhat-cop/cert-utils-operator
      branch: master
      tags: false
      #all_branches: true
  - provider: script
    skip_cleanup: true
    script: make travis-release-deploy
    on:
      repo: redhat-cop/cert-utils-operator
      branch: master
      tags: true
      #all_branches: true
